import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/quiz/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'
import { useState, useEffect,useRef } from 'react';

export default function Main_menu() {
  const router = useRouter()

  const [inputValue1, setInputValue1] = useState('');
  const [inputValue2, setInputValue2] = useState('');
  const [inputValue3, setInputValue3] = useState('');

  const handleInputChange1 = (event) => {
    setInputValue1(event.target.value);
  }
  const handleInputChange2 = (event) => {
    setInputValue2(event.target.value);
  }
  const handleInputChange3 = (event) => {
    setInputValue3(event.target.value);
  }

  const checkAns = () => {
    if (inputValue1.toLowerCase() == 'unconciousness' || inputValue2.toLowerCase() == 'patient movement'  || inputValue3.toLowerCase() == 'pain perception') {
      router.push('/mainbrain')
    } else {
      router.push('/hint/brain-false')
    }
   
    
  }

  const ansCorrect = () => {
    router.push('/hint/brain-ture')
  }
  const ansWorng = () => {
    router.push('/hint/brain-false')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/case/brain/1"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className={styles.quiz_container}>
        <div className='container'>
          <div className='row justify-content-center align-items-center min-h-screen'>
            
            <div className='col-11 col-lg-8'>
              <section className={styles.bgTriangle}>
                <h1 className={styles.quiz_title}>Triad of Anesthesia ประกอบด้วยอะไร</h1>
                <div className='row justify-content-center'>
                  <div className='col-4'>
                    <h2 className={styles.quiz_subtitle}>
                    Anesthetics
                    </h2>
                    <input type="text" className="form-control" placeholder='' onChange={handleInputChange1}/>
                  </div>
                  <div className='col-12'>
                    <div className={styles.blankSpace}></div>
                  </div>
                  <div className='col-4'>
                    <h2 className={styles.quiz_subtitle}>
                      Muscle
                      relaxants
                    </h2>
                    <input type="text" className="form-control" placeholder='' onChange={handleInputChange2}/>
                  </div>
                  <div className='col-4'>
                    
                  </div>
                  <div className='col-4'>
                    <h2 className={styles.quiz_subtitle}>
                      Analgesics
                    </h2>
                    <input type="text" className="form-control" placeholder='' onChange={handleInputChange3}/>
                  </div>

                  <div className='col-12 mt-5'>
                    <div className={styles.btn_area}>
                      <div className={styles.btn_container}>
                          <button className={styles.next_btn} onClick={checkAns}>
                          NEXT
                          </button>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  )
}