import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/quiz/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'


export default function Main_menu() {
  const router = useRouter()

  const ansCorrect = () => {
    router.push('/hint/brain-ture')
  }
  const ansWorng = () => {
    router.push('/hint/brain-false')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/case/brain/1"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className={styles.quiz_container}>
        <div className='container'>
          <div className='row justify-content-center align-items-center min-h-screen'>
            <div className='col-11 col-lg-8'>
              <h1 className={styles.quiz_title}>จากสภาวะดังกล่าวของคนไข้ ท่านจะมีวิธีจัดการดูแลคนไข้อย่างไร</h1>
              <div className={styles.quiz_lists}>                
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>เพิ่มระดับของยาระงับความรู้สึก</p>
                </div>
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>ลดระดับของยาระงับความรู้สึก</p>
                </div>
                <div className={styles.quiz_item} onClick={ansCorrect}>
                  <p>ขอ Brain monitoring มาใช้ในการประเมินคนไข้เพื่อวางแผนในการรักษา หรือใช้ร่วมกับการวางแผนการใช้ยาระงับความรู้สึกให้กับคนไข้</p>
                </div>
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>ลดระดับของยา Neuromuscular blockade</p>
                </div>
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>ส่งคนไข้ทำ CT brain เพราะสงสัยstroke</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}