import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/quiz/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'
import { useState, useEffect,useRef } from 'react';
import Lottie from 'react-lottie';
import animationData from '../../lottiefiles/checkmark.json';
export default function Main_menu() {
  const router = useRouter()

  const [inputValue1, setInputValue1] = useState('');
  const [inputValue2, setInputValue2] = useState('');
  const [inputValue3, setInputValue3] = useState('');

  const [showLottie, setShowLottie] = useState(false);

  const handleInputChange1 = (event) => {
    setInputValue1(event.target.value);
  }
  const handleInputChange2 = (event) => {
    setInputValue2(event.target.value);
  }
  const handleInputChange3 = (event) => {
    setInputValue3(event.target.value);
  }

  const checkAns = () => {
    if (inputValue1.toLowerCase() == 'unconciousness' || inputValue2.toLowerCase() == 'patient movement'  || inputValue3.toLowerCase() == 'pain perception') {
      // router.push('/mainbrain')
      router.push('/success/brain')
    } else {
      router.push('/hint/brain-false')
    }
   
    
  }


  // lottie
  const lottieOptions = {
    animationData: animationData,
    // loop: true,
    loop: false,
    autoplay: true,
    rendererSettings: {
      // preserveAspectRatio: 'xMidYMid slice'
      preserveAspectRatio: 'none'
    }
  };

  const ansCorrect = () => {
    // router.push('/mainbrain')    
    setShowLottie(true)
    setTimeout(() => { 
      setShowLottie(false)
      router.push('/success/brain')
    }, 2000)
  }
  const ansWorng = () => {
    router.push('/hint/brain-false')
  }
  return (
    <div className={styles.container}>
      {showLottie &&
        <div className={styles.lottieCheck}>
          <Lottie options={lottieOptions} />
        </div>
      }
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/case/brain/1"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className={styles.quiz_container}>
        <div className='container'>
          <div className='row justify-content-center align-items-center min-h-screen'>
            <div className='col-11 col-lg-8'>
              <h1 className={styles.quiz_title}>
              ผู้ป่วย post-cardiac arrest ได้รับการช่วยหายใจด้วยเครื่องช่วยหายใจ โดยได้รับยาระงับความรู้สึกและยาหย่อนกล้ามเนื้อ
              ขณะนั้นผู้ป่วยกำลังได้รับการทำ Targeted Temperature Management (TTM) ค่าสัญญาญของผู้ป่วยคงที่ ไม่มีการเปลี่ยนแปลงของพารามิเตอร์ของการหายใจ ค่า RASS score เท่ากับ -5 โดยค่า BIS เพิ่มขึ้นจาก 40 เป็น 70
              หากท่านได้ให้การดูแลผู้ป่วยรายนี้ ท่านจะให้การรักษาเบื้องต้นใด เป็นอย่างแรก
              </h1>
              <div className={styles.quiz_lists}>                
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>เพิ่มขนาดยาระงับความรู้สึก</p>
                </div>
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>เพิ่มขนาดยาหย่อนกล้ามเนื้อ</p>
                </div>
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>ตรวจสอบ Arterial Blood Gas</p>
                </div>
                <div className={styles.quiz_item} onClick={ansCorrect}>
                  <p>ตรวจสอบระดับเฟสของ TTM <br/>
                    (Cooling phase หรือ Rewarm phase)</p>
                </div>                
                <div className={styles.quiz_item} onClick={ansWorng}>
                  <p>สังเกตอาการต่อ โดยไม่ทำการรักษาเพิ่มเติม</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}