import Head from 'next/head'
import { useState , useEffect } from 'react';
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/brain/sensor.module.scss'
import Link from "next/link";

export default function Howto() {
  const [message, setMessage] = useState(null);
  return (
    <div className={styles.container}>
      <Head>
        
        <title>Sensor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/mainbrain"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className={styles.page_wrapper}>
        <div className={styles.BrainMonitoring}>
            <Image
                src="/images/BrainMonitoring-item.png"
                alt="Women"
                className={styles.BrainMonitoring_item}
                // layout="fill"
                // objectFit="cover"
                width={1952}
                height={1824}
            />
        </div>
        <div className={styles.Bis_wrap}>
          <div className={styles.BisItem_wrap}>
          <Image
                src="/images/bis-item-2.png"
                alt="Women"
                className={styles.Bis_item}
                // layout="fill"
                // objectFit="cover"
                width={1733}
                height={201}
            />
          </div>
        </div>
        <div className={styles.btn_group}>
            <button>
            Confirm
            </button>
        </div>
      </div>
    </div>
  )
}