import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/vent/instruction.module.scss'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function Demo() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DEMO </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/consemt"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
        <div className='text-center'>
            <Image
                src="/images/vent-demo.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={800}
                height={800}
            />
        </div>
        <div className='text-center pb-4'>
            <a href='https://sim.orainteractive.com/' target='_blank' rel='noreferrer'>
                Link to simulator
            </a>
        </div>
    </div>
  )
}