import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/vent/instruction.module.scss'
import Link from "next/link";
import VentInto from '../../components/ventinto-backup-full-button'


export default function Instruction() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instruction </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menulearningmode"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className={styles.row}>
        <div className={styles.col}>
          <VentInto />
        </div>
      </div>
    </div>
  )
}