import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/vent/quiz0.module.scss'
import Link from "next/link";
import VentInto from '../../components/ventinto'
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router'

import Lottie from 'react-lottie';
import animationData from '../../lottiefiles/checkmark.json';

export default function Instruction() {
  const router = useRouter()
  
  const [currentColor, setCurrentColor] = useState('');
  const [currentStep, setCurrentStep] = useState('');
  const [dataSelection, setDataSelection] = useState({
    TidalVolume: '',
    MinuteVentilation : '',
    PIP : '',
    P_rise : '',
    PEEP : ''
  });
  const [showLottie, setShowLottie] = useState(false);

  // lottie
  const lottieOptions = {
    animationData: animationData,
    // loop: true,
    loop: false,
    autoplay: true,
    rendererSettings: {
      // preserveAspectRatio: 'xMidYMid slice'
      preserveAspectRatio: 'none'
    }
  };


  const handleSettingbtn = (event) => {

      document.querySelector(`.${styles.btnOrangeOutline}`).classList.remove(styles['btnOutlineActive']);
      document.querySelector(`.${styles.btnRedOutline}`).classList.remove(styles['btnOutlineActive']);
      document.querySelector(`.${styles.btnBlueOutline}`).classList.remove(styles['btnOutlineActive']);
      document.querySelector(`.${styles.btnGreenOutline}`).classList.remove(styles['btnOutlineActive']);
      document.querySelector(`.${styles.btnPinkOutline}`).classList.remove(styles['btnOutlineActive']);


      event.currentTarget.classList.add(styles['btnOutlineActive']);

      const btnStep = event.currentTarget.getAttribute('data-step');
      const btnColor = event.currentTarget.getAttribute('data-color');
      setCurrentStep(btnStep)
      setCurrentColor(btnColor)

  }

  const handleSelectbtn = (event) => {
      if (currentStep == '') {
        alert('กรุณาเลือกคำถาม')
      } else {

        let btnName = event.currentTarget.getAttribute('data-btnName');

        event.currentTarget.classList.remove(styles['btnGray']);
        event.currentTarget.classList.remove(styles['btnOrange']);
        event.currentTarget.classList.remove(styles['btnRed']);
        event.currentTarget.classList.remove(styles['btnBlue']);
        event.currentTarget.classList.remove(styles['btnGreen']);
        event.currentTarget.classList.remove(styles['btnPink']);

        event.currentTarget.classList.add(styles['btn'+currentColor]);


        dataSelection.TidalVolume = dataSelection.TidalVolume.replace(btnName + ", ", "").replace(btnName, "");
        dataSelection.MinuteVentilation = dataSelection.MinuteVentilation.replace(btnName + ", ", "").replace(btnName, "");
        dataSelection.PIP = dataSelection.PIP.replace(btnName + ", ", "").replace(btnName, "");
        dataSelection.P_rise = dataSelection.P_rise.replace(btnName + ", ", "").replace(btnName, "");
        dataSelection.PEEP = dataSelection.PEEP.replace(btnName + ", ", "").replace(btnName, "");

        // Checking for duplicate value
        if (dataSelection[currentStep].includes(btnName)) {
          console.log("Duplicate data found!");
        } else {
          dataSelection[currentStep] += btnName + ", ";
        }
        
        setDataSelection(dataSelection)

        console.log(dataSelection)

      }

      
  }

  const handleSubmit = () => {
    if(
      
      dataSelection['TidalVolume'].includes('ปริมาตรอากาศที่ไหลเข้าถุงลมต่อหนึ่งครั้ง') &&
      dataSelection['MinuteVentilation'].includes('VT x RR') &&
      dataSelection['MinuteVentilation'].includes('ปริมาตรอากาศที่เข้าสู่ปอดของผู้ป่วยใน 1 นาที') &&
      dataSelection['PIP'].includes('Peak Inspiration pressure') &&
      dataSelection['PIP'].includes('Peak airway pressure') &&
      dataSelection['P_rise'].includes('Pressurization slope') &&
      dataSelection['P_rise'].includes('อัตราเร่งการไหลของลมขณะหายใจเข้า') &&
      dataSelection['P_rise'].includes('มีความสัมพันธ์กับการไหลของลมขณะหายใจเข้า') &&
      dataSelection['PEEP'].includes('Positive End Expiratory Pressure') &&
      dataSelection['PEEP'].includes('แรงดันบวกของอากาศหายใจที่ค้างอยู่ในปอดเมื่อสิ้นสุดการหายใจออก')
    
      ) {
        
        console.log('ถูก')

        setShowLottie(true)

        const mainWrap = document.querySelector('#main')
        mainWrap.classList.add(styles['hidden']);
        mainWrap.classList.remove(styles['flade']);
        setTimeout(() => { 
          // mainWrap.classList.remove(styles['hidden']);
          // mainWrap.classList.add(styles['flade']);

          setShowLottie(false)

          router.push('/vent/quiz')
        }, 2000)


    } else {
      // alert('ผิด')
      router.push('/hint/brain-false')
    }
  }
  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Instruction </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menulearningmode"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className='container'>
          {showLottie &&
          <div className={styles.lottieCheck}>
            <Lottie options={lottieOptions} />
          </div>
          }    
          <main id='main'>
            <section className='pt-5'>
              <div className={styles.quiz_title}>
                จับคู่ กด ชื่อ กดคำอธิบาย เปลี่ยนสีตามคำที่เลือก
              </div>
            </section>

            <section className='pt-4'>
              <div className={styles.boxGrid}>         
                <button className={styles.btnOrangeOutline} data-step='TidalVolume' data-color='Orange' onClick={handleSettingbtn}>
                  Tidal Volume
                </button>
                <button className={styles.btnRedOutline} data-step='MinuteVentilation' data-color='Red' onClick={handleSettingbtn}>
                Minute <br/>
                Ventilation
                </button>
                <button className={styles.btnBlueOutline} data-step='PIP' data-color='Blue' onClick={handleSettingbtn}>
                  PIP
                </button>
                <button className={styles.btnGreenOutline} data-step='P_rise' data-color='Green' onClick={handleSettingbtn}>
                  P rise
                </button>
                <button className={styles.btnPinkOutline} data-step='PEEP' data-color='Pink' onClick={handleSettingbtn}>
                  PEEP
                </button>
              </div>
            </section>

            <section>
              <hr></hr>
            </section>

            <section className='pt-4'>
              <div className={styles.boxGrid}>         
                <button className={styles.btnGray} data-btnName='VT x RR' onClick={handleSelectbtn}>
                  VT x RR
                </button>
                <button className={styles.btnGray} data-btnName='Pressurization slope' onClick={handleSelectbtn}>
                Pressurization slope
                </button>
                <button className={styles.btnGray} data-btnName='ปริมาตรอากาศที่เข้าสู่ปอดของผู้ป่วยใน 1 นาที' onClick={handleSelectbtn}>
                ปริมาตรอากาศที่เข้าสู่ปอดของผู้ป่วยใน 1 นาที
                </button>
                <button className={styles.btnGray} data-btnName='Peak Inspiration pressure' onClick={handleSelectbtn}>
                Peak Inspiration pressure
                </button>
                <button className={styles.btnGray} data-btnName='Positive End Expiratory Pressure' onClick={handleSelectbtn}>
                Positive End Expiratory Pressure
                </button>

                <button className={styles.btnGray} data-btnName='อัตราเร่งการไหลของลมขณะหายใจเข้า' onClick={handleSelectbtn}>
                อัตราเร่งการไหลของลมขณะหายใจเข้า
                </button>
                <button className={styles.btnGray} data-btnName='Peak airway pressure' onClick={handleSelectbtn}>
                Peak airway pressure
                </button>
                <button className={styles.btnGraySm} data-btnName='แรงดันบวกของอากาศหายใจที่ค้างอยู่ในปอดเมื่อสิ้นสุดการหายใจออก' onClick={handleSelectbtn}>
                แรงดันบวกของอากาศหายใจที่ค้างอยู่ในปอดเมื่อสิ้นสุดการหายใจออก
                </button>
                <button className={styles.btnGray} data-btnName='ปริมาตรอากาศที่ไหลเข้าถุงลมต่อหนึ่งครั้ง' onClick={handleSelectbtn}>
                ปริมาตรอากาศที่ไหลเข้าถุงลมต่อหนึ่งครั้ง
                </button>
                <button className={styles.btnGray} data-btnName='มีความสัมพันธ์กับการไหลของลมขณะหายใจเข้า' onClick={handleSelectbtn}>
                มีความสัมพันธ์กับการไหลของลมขณะหายใจเข้า
                </button>
              </div>
            </section>
            <section className='text-end w-100 mt-5'>
              <button className={styles.btnSubmit} onClick={handleSubmit}>
                  SUBMIT
              </button>
            </section>
          </main>
          
      </div>
    </div>
  )
}