import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/vent/sim.module.scss'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function Sim() {
  return (
    <div className={styles.container}>
      <Head>        
        <title>Sim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://unpkg.com/@ungap/custom-elements-builtin"></script>
        <script src="https://wish-integrate.com/x-frame-bypass/x-frame-bypass.js"></script> */}
      </Head>
      <div className='prev_page'>
          <Link href="/consemt"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      
      <div className={styles.iframe_container}>
        {/* <iframe 
        is='x-frame-bypass'
        loading='lazy'  
        src="https://sim.orainteractive.com/" 
        ></iframe> */}
      </div>
    </div>
  )
}