import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/casedetail.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function CaseDetail() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Trouble shooting </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menulearningmode"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div className='container'>
        <div className='row justify-content-center align-items-center min-h-screen'>
          <div className='col-11'>
            <div className={styles.case_wrapper}>
              {/* <div className='prev_page_case'>
                <Link href="/menulearningmode"> 
                  <Image
                      src="/images/prev.png"
                      alt="Women"
                      // layout="fill"
                      // objectFit="cover"
                      width={196}
                      height={196}
                  />
                  </Link>
              </div> */}
              <div className={styles.case_row}>
                <div className={styles.case_colleft}>
                  {/* <div className={styles.case_thumbnail}>
                    <Image
                        src="/images/card1-rounded.png"
                        alt="case1"
                        width={500}
                        height={500}
                    />
                  </div> */}
                  <div className={styles.case_thumbnail2}>
                    <Image
                        src="/images/case1-thumb3.png"
                        alt="case1"
                        width={500}
                        height={500}
                    />
                  </div>
                  <div className={styles.case_simpledetail}>
                    <h2 className={styles.case_name}>Patient 3</h2>
                    <div className={styles.case_simpledetail_byline}>
                      <ul>
                        <li>
                          Age : <strong>60</strong>
                        </li>
                        <li>
                          Sex : <strong>Male</strong>
                        </li>
                        <li>
                          Weight : <strong>67 kg</strong>
                        </li>
                        <li>
                          Height : <strong>170 Cm</strong>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div className={styles.case_colright}>
                  <div className={styles.right_row}>
                    <div className={styles.right_colbox}>
                      <div className={styles.detail_row_short}>
                        <div className={styles.detail_colfull}>
                          <div className={styles.case_fulldetail}>
                            {/* <p>
                            มาช่วยตั้งค่าเครื่องช่วยหายใจให้คนไข้คนนี้กัน
                            </p>
                            <p>
                            ผู้ป่วยใส่ท่อช่วยหายใจ สามารถหายใจเองได้ 
                            </p>
                            <p>
                            คุณหมอต้องการตั้งเครื่องช่วยหายใจเพื่อช่วยให้คนไข้หายใจสบายขึ้น
                            </p> */}
                            <p>                              
                            ผู้ป่วยได้รับการใส่ท่อช่วยหายใจจากภาวะหายใจหอบเหนื่อยแต่ผู้ป่วยยังคงสามารถหายใจได้ด้วยตัวเอง 
                            ผู้ป่วยได้รับการตั้งค่าโหมดเครื่องช่วยหายใจเรียบร้อยแล้ว ให้ท่านช่วยกดปุ่มตั้งค่าพารามิเตอร์ตามค่าที่ได้กำหนดไว้
                            </p>

                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <div className={styles.btn_monitor_thumbnail_area}>
                    <div className={styles.btn_monitor_thumbnail}>
                      <Link href="/case/monitor/3"> 
                      <Image
                          src="/images/monitor.png"
                          alt="case1"
                          // layout="fill"
                          // objectFit="cover"
                          width={500}
                          height={500}
                      />
                      </Link>
                    </div>
                  </div> */}
                  <div className={styles.btn_area}>
                    <Link href='/vent/test'>
                    <button className={styles.next_btn}>
                      NEXT
                    </button>
                    </Link>                    
                  </div>
                </div>
                {/* case_colright */}
              </div>
            </div> 
          </div>          
        </div>
      </div>
    </div>
  )
}