import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/trouble-shooting/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'
import Trouble2 from '../../components/trouble-shooting-2'

export default function Main_menu() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Trouble Shooting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Trouble2 />
    </div>
  )
}