import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/consent.module.css'
import Link from "next/link";
import { useRouter } from 'next/router'

export default function Consent() {
    const router = useRouter()
    function toWelcomePage() {
        router.push('/welcome')
    }
    return (
        <div className={styles.container}>
        <Head>
            <title>Consent</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='prev_page'>
            <Link href="/select"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
        </div>{/* prev_page */}
        <div className={styles.row}>
            <div className={styles.col}>
                <div className={styles.card}>
                    <h1>Consent Form</h1>
                    <div className={styles.card_body}>
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                            molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                            numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                            optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
                            obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
                            nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,
                            tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,
                            quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos 
                            sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam
                            recusandae alias error harum maxime adipisci amet laborum. Perspiciatis 
                            minima nesciunt dolorem! Officiis iure rerum voluptates a cumque velit 
                            quibusdam sed amet tempora. Sit laborum ab, eius fugit doloribus tenetur 
                            fugiat, temporibus enim commodi iusto libero magni deleniti quod quam 
                            consequuntur! Commodi minima excepturi repudiandae velit hic maxime
                            doloremque. Quaerat provident commodi consectetur veniam similique ad 
                            earum omnis ipsum saepe, voluptas, hic voluptates pariatur est explicabo 
                            fugiat, dolorum eligendi quam cupiditate excepturi mollitia maiores labore 
                            suscipit quas? Nulla, placeat. Voluptatem quaerat non architecto ab laudantium
                            modi minima sunt esse temporibus sint culpa, recusandae aliquam numquam 
                            totam ratione voluptas quod exercitationem fuga. Possimus quis earum veniam 
                            quasi aliquam eligendi, placeat qui corporis!
                        </p>
                    </div>
                    <div className={styles.btn_area}>
                        <button 
                        onClick={toWelcomePage} 
                        className={styles.submit_btn}>
                            Accept
                        </button>
                    </div>
                </div>
            </div>
        </div>
        </div>
    )
}
