import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/consent.module.css'
import Link from "next/link";
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';

// เปลี่ยน BG

export default function Consent() {
    const [check1, setCheck1] = useState(false);
    const [check2, setCheck2] = useState(false);
    const [check3, setCheck3] = useState(false);
    const [check4, setCheck4] = useState(false);
    const router = useRouter()
    function toWelcomePage() {
        if (check1 && check2 && check3 && check4) {
            router.push('/welcome')
        } else {
            const endElement = document.getElementById("checkbox2");
            endElement.scrollIntoView({ behavior: 'smooth'});

            document.getElementById("alert_text").classList.add(styles['show_alert_text']);
        }
    }
    return (
        <div className={styles.container}>
        <Head>
            <title>Consent</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='prev_page'>
            <Link href="/select"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
        </div>{/* prev_page */}
        <div className={styles.row}>
            <div className={styles.col}>
                <div className={styles.card}>
                    <h1>Consent Form</h1>
                    <div className={styles.card_body}>
                        
                        <p>
                            โปรดอ่านเอกสารให้ความยินยอมนี้อย่างละเอียดและลงชื่อตามที่ระบุไว้ด้านล่าง 
                        </p>
                        <p>
                        เราต้องการความยินยอมจากท่านในการเก็บรวบรวมข้อมูลของท่านและใช้ข้อมูลที่ท่านให้ไว้ตามที่กำหนดไว้ในนโยบายความเป็นส่วนตัวของเรา ซึ่งมีข้อมูลโดยละเอียดเกี่ยวกับการเก็บรวบรวม การใช้ และการเปิดเผยข้อมูลของท่าน สามารถอ่านนโยบายความเป็นส่วนตัวของเราได้ที่ <a href='https://asiapac.medtronic.com/xp-en/privacy-statement.html'>https://asiapac.medtronic.com/xp-en/privacy-statement.html</a> <br/>หรือท่านสามารถขอสำเนานโยบายความเป็นส่วนตัวของเราได้จากตัวแทนของ Medtronic
                        </p>
                        <p>
                        ข้อมูลที่ Medtronic เก็บรวบรวมประกอบด้วย ชื่อ นามสกุล อีเมล หมายเลขโทรศัพท์ ที่อยู่ทางไปรษณีย์/รหัสไปรษณีย์ อาชีพ กลุ่มบำบัด ความเชี่ยวชาญหลักทางการแพทย์ ชื่อโรงพยาบาล/คลินิก เมือง ประเทศที่ปฏิบัติเวชกรรม ในกรณีที่กฎหมายภายในประเทศกำหนด จะมีการเก็บหมายเลขประจำตัวของแพทย์ พยาบาล และหมายเลขวิชาชีพที่เกี่ยวข้อง
                        </p>
                        <p>
                        โดยทั่วไปแล้ว เราจะใช้ข้อมูลของท่านเพื่อวัตถุประสงค์ตามรายการด้านล่าง ซึ่งรวมถึงแต่ไม่จำกัดเพียง:
                        </p>
                        <ul>
                            <li>การแนะนำผลิตภัณฑ์ การรับคำสั่งซื้อและการจัดหา และการสื่อสารที่เกี่ยวข้อง</li>
                            <li>การทำให้มั่นใจว่าผลิตภัณฑ์จะมีความปลอดภัย คุณภาพ ประสิทธิภาพ และการใช้งานอย่างเหมาะสม และการรวบรวม ตรวจสอบ วิเคราะห์ จัดหา และจัดเตรียมข้อมูลตามที่กล่าวมา</li>
                            <li>การตรวจสอบ วิเคราะห์ และวิจัยในสาขาการแพทย์ วิศวกรรมชีวภาพ และเภสัชกรรม ตลอดจนคำขอ การสนับสนุน และการจัดการต่าง ๆ</li>
                            <li>การรวบรวม สำรวจ วิเคราะห์ จัดหา และจัดเตรียมข้อมูลทางการแพทย์และวิชาการ</li>
                            <li>การร้องขอการบรรยายและการสาธิตเกี่ยวกับผลิตภัณฑ์ ยา วิศวกรรมชีวภาพ ฯลฯ และคำแนะนำ คำเชิญ การดำเนินงาน และการจัดการการบรรยายและการสาธิต ฯลฯ</li>
                            <li>การพัฒนาผลิตภัณฑ์ การวิจัยทางคลินิก การทดลองทางคลินิกและคำขอดังกล่าว คำขอสำหรับการดูแลผลิตภัณฑ์ การสำรวจ การวิเคราะห์ และคำขอผลิตภัณฑ์หลังการขาย</li>
                            <li>การรวบรวมและการจัดการข้อมูลการรับเงินและการประมวลผลการชำระเงิน</li>
                            <li>การจัดหาและการเปิดเผยข้อมูลเพื่อให้มีความโปร่งใสในการจ่ายเงิน ฯลฯ</li>
                            <li>การวางแผนและการนำผลิตภัณฑ์ บริการ และการดำเนินงานของบริษัท Medtronic plc และบริษัทในเครือมาใช้</li>
                            <li>ให้ข้อมูลผลิตภัณฑ์หรือความปลอดภัยที่อัปเดตล่าสุดเกี่ยวกับอุปกรณ์ แอป และบริการทางการแพทย์ของ Medtronic แก่ท่าน</li>
                            <li>ส่งเอกสารเกี่ยวกับกิจกรรมและผลิตภัณฑ์ของเราหรือการพัฒนาเทคโนโลยีทางการแพทย์ที่ Medtronic เชื่อว่าท่านอาจสนใจให้แก่ท่าน</li>
                            <li>ตอบสนองต่อคำขอของท่านสำหรับข้อมูล ผลิตภัณฑ์ บริการ รวมถึงการจัดการบัญชีออนไลน์ของท่านและให้บริการการรับประกันในกรณีที่ใช้กับผลิตภัณฑ์</li>
                            <li>บริหาร วางแผน และจัดการประชุมระหว่างท่านและตัวแทนของ Medtronic</li>
                            <li>ปกป้องความปลอดภัยด้านสุขภาพหรือสวัสดิการของใครบางคน</li>
                            <li>ปฏิบัติตามกฎหมายหรือระเบียบ คำสั่งศาล หรือข้อกำหนดทางกฎหมายอื่น ๆ</li>
                        </ul>
                        <p>
                        ในฐานะที่เป็นส่วนหนึ่งของกลุ่มบริษัทข้ามชาติ เราอาจเปิดเผยข้อมูลของท่านแก่บริษัทหรือฐานข้อมูลของ Medtronic ในต่างประเทศ แต่เราจะตรวจสอบให้แน่ใจว่าการใช้และการเปิดเผยข้อมูลส่วนบุคคลที่ถ่ายโอนจะได้รับการจัดการตามนโยบายนี้และการป้องกันภายใต้กฎหมายที่บังคับใช้
                        </p>
                        <div className='row g-1 mb-4 pt-4'>
                            <div className='col-9 col-lg-11'>
                                <label for="checkbox1"> ข้าพเจ้าได้อ่านข้อมูลข้างต้นแล้วและเข้าใจว่าเหตุใดข้อมูลของข้าพเจ้าจึงถูกรวบรวมโดย Medtronic</label>
                            </div>
                            <div className='col-3 col-lg-1 text-end'>
                                <input className={styles.checkboxItem} type="checkbox" 
                                defaultChecked={check1}
                                onChange={() => setCheck1(!check1)}
                                id="checkbox1" 
                                name="checkbox1" 
                                value="checkbox1" />
                            </div>                          
                        </div>
                        <div className='row g-1 mb-4'>
                            <div className='col-9 col-lg-11'>
                                <label for="checkbox2"> ข้าพเจ้าเข้าใจว่าข้าพเจ้าไม่จำเป็นต้องให้ข้อมูลใด ๆ ที่ร้องขอจากข้าพเจ้า แต่การไม่ทำเช่นนั้นจะทำให้ได้รับการสนับสนุนทางเทคนิคจาก Medtronic ลดลง</label>
                            </div>
                            <div className='col-3 col-lg-1 text-end'>
                                <input className={styles.checkboxItem} type="checkbox" 
                                defaultChecked={check2}
                                onChange={() => setCheck2(!check2)}
                                id="checkbox2" name="checkbox2" value="checkbox2" />
                            </div>                          
                        </div>
                        <div className='row g-1 mb-4'>
                            <div className='col-9 col-lg-11'>
                                <label for="checkbox3"> ข้าพเจ้ารับทราบถึงสิทธิ์ของข้าพเจ้าในการเข้าถึงข้อมูลที่รวบรวมเกี่ยวกับตัวข้าพเจ้า ยกเว้นในบางกรณีที่การเข้าถึงอาจถูกระงับโดยชอบด้วยกฎหมาย (โดยที่ข้าพเจ้าจะได้รับคำอธิบายในสถานการณ์เหล่านี้)</label>
                            </div>
                            <div className='col-3 col-lg-1 text-end'>
                                <input className={styles.checkboxItem} type="checkbox" 
                                defaultChecked={check3}
                                onChange={() => setCheck3(!check3)}
                                id="checkbox3" name="checkbox3" value="checkbox3" />
                            </div>                          
                        </div>
                        <div className='row g-1'>
                            <div className='col-9 col-lg-11'>
                                <label for="checkbox4"> ข้าพเจ้ายินยอมให้ Medtronic จัดการข้อมูลของข้าพเจ้าตามวัตถุประสงค์ที่กำหนดไว้ข้างต้น</label>
                            </div>
                            <div className='col-3 col-lg-1 text-end'>
                                <input className={styles.checkboxItem} type="checkbox" 
                                defaultChecked={check4}
                                onChange={() => setCheck4(!check4)}
                                id="checkbox4" name="checkbox4" value="checkbox4" />
                            </div>                          
                        </div>
                    </div>
                    <div id='alert_text' className={styles.alert_text}>
                        <p className='text-center text-danger'>
                        กรุณาเลือกแสดงความยินยอมในกล่องสี่เหลี่ยมทุกข้อก่อนตกลง
                        </p>
                    </div>
                    <div className={styles.btn_area}>
                        <button 
                        onClick={toWelcomePage} 
                        className={styles.submit_btn}>
                            Accept
                        </button>
                    </div>
                </div>
            </div>
        </div>
        </div>
    )
}
