import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
// import styles from '../styles/mainmenu2.module.css'
import styles from '../styles/mainmenu.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


import axios from 'axios';
import { useState } from 'react';

export default function Main_menu() {

  const [response, setResponse] = useState('');
  const [data, setData] = useState('');
  const [signature, setSignature] = useState('');

  const sendData = async () => {
    try {
      const dataToSend = {
        data: data,
        signature: signature,
      };

      const response = await axios.post('http://localhost:3000/api/cvlearn', dataToSend);
      setResponse(response.data);
    } catch (error) {
      console.error('เกิดข้อผิดพลาดในการส่งข้อมูลไปที่เว็บไซต์ B:', error);
    }
  };
  
  return (
    <div className={styles.container}>
        <Head>
        <title>Test Form CV Learn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="container">
        <div className="row justify-content-center">
            <div className="col-10">
                <div>
                  <textarea
                      className='w-100'
                      type="text"
                      value={data}
                      onChange={(e) => setData(e.target.value)}
                      placeholder="data"
                  />



                  <textarea
                      className='w-100'
                      type="text"
                      value={signature}
                      onChange={(e) => setSignature(e.target.value)}
                      placeholder="signature"
                  />

                  <button className='w-100' onClick={sendData}>ส่งข้อมูลไปที่เว็บ B</button>

                  {response && <p>เว็บ B ตอบกลับ: {JSON.stringify(response)}</p>}
                </div>
            </div>
        </div>          


        </main>



    </div>
  )
}