import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react';
import { useRouter } from 'next/router'
import HomeAlert from '../components/homealert'

export default function Home() {
  const router = useRouter()
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState(null);
  const handleChange = event => {
    setPassword(event.target.value);
    console.log('value is:', event.target.value);    
    setMessage(null);
  };

  const checkPassword = () => {
    const correctPassword = '9876543';
    if (password === correctPassword) {
      router.push('/select');
    } else {
      setMessage('Incorrect password');
    }
  };

  // Elements
  const alertElement = message ? <HomeAlert message={message} /> : null;

  return (
    <div className={styles.container}>
      <Head>
        <title>i-MEDucation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.login_page}>
        <div className={styles.login_container}>
          <p>password :: 9876543</p>
          <p>{alertElement}</p>
          <input 
          className={styles.login_input} 
          type="text" 
          placeholder='Enter Password'
          onChange={handleChange}
          value={password} />

          <button 
          onClick={checkPassword}
          className={styles.submit_btn}>Login</button>
        </div>        
      </div>
    </div>
  )
}
