import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState , useEffect} from 'react';
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const [password, setPassword] = useState('');
  const [dataUser, setDataUser] = useState({});

  const handleChange = event => {
    setPassword(event.target.value);
    console.log('value is:', event.target.value);    
  };

  const checkPassword = () => {
    const correctPassword = '9876543';
    if (password === correctPassword) {
      // router.push('/select');
      router.push('/welcome');
    } else {
      setMessage('Incorrect password');
    }
  };

  const handleRegister = () => {
    router.push('/select');
  }

  // Elements


  async function handleSubmit(event) {
    event.preventDefault();
  
    const formData = {
      otp: password,
    };
  
    const res = await fetch('https://ventbackend.wish-integrate.com/otp-login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(formData),
    });
  
    const data = await res.json();
    console.log(data);
    console.log(data.status);
    console.log(data.user.name);
    setDataUser(data);

    // Save to local Storage
    localStorage.setItem('userData', JSON.stringify(data));
    setUserData(data);
  }

  const [userData, setUserData] = useState({});

  useEffect(() => {
    const storedData = localStorage.getItem('userData');
    if (storedData) {
      setUserData(JSON.parse(storedData));
      console.log(storedData)
    }
  }, []);

  const handleClear = () => {
    localStorage.removeItem('userData');
    setUserData({});
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Med U More OTP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.login_page}>
        <div className={styles.login_container}>
          <h1>MedUmore OTP</h1>
          <form onSubmit={handleSubmit}>
          <input 
          className={styles.login_input} 
          type="text" 
          name="pin"
          placeholder='Enter OTP'
          onChange={handleChange}
          value={password} />

          <div className={styles.btn_group}>
            <div>
              <button 
              onClick={handleSubmit}
              className={styles.submit_btn}>Login</button>          
            </div>
          </div>

          </form>

          {/* {!dataUser.status.includes('success') &&
          <div>
            <p>{dataUser.status}</p>
            <p>{dataUser.user.name}</p>
            <p>{dataUser.user.lastname}</p>
            <p>{dataUser.user.utoken}</p>
          </div>
          } */}

          <div className={styles.btn_group}>
            <div>
              <button 
              onClick={handleClear}
              className={styles.submit_btn}>Logout</button>          
            </div>
          </div>

        </div>        
      </div>
    </div>
  )
}
