import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/mainmenu.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function menu3() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Main Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/consent"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <header className='headerbar1'>
        <p className='headerbar_text'>
        Main Menu
        </p>
      </header>
      <div className={styles.row}>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/menuventilator"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/Ventilator-thumbnail.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Ventilator
              </p>
            </div>   
            </Link>         
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
          <Link href="/mainbrain"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/BrainMonitoring-thumbnail-crop.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Brain Monitoring
              </p>
            </div>    
            </Link>           
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/Result-thumbnail.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={504}
                    height={620}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Result
              </p>
            </div>            
          </div>
        </div>
      </div>
    </div>
  )
}