import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/mainmenuBrain.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function menu3() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Brain Monitoring Setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/mainmenu"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <header className={styles.headerbar1}>
        <p className='headerbar_text'>
        Brain Monitoring Setup
        </p>
      </header>
      <div className={styles.row}>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/instruction/equipmentsetup"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/BrainMonitoring.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Equipment Set Up
              </p>
            </div>   
            </Link>         
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/instruction/sensorplacement"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/sensorcheck-thumbnail.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Sensor Placement
              </p>
            </div> 
            </Link>             
          </div>
        </div>
      </div>
    </div>
  )
}