import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/menu2.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function menu2() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Trouble shooting </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menulearningmode">
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <header className={styles.headerbar1}>
        <p className='headerbar_text'>
        Trouble shooting 
        </p>
      </header>
      <div className={styles.row}>
        <div className={styles.col_item}>
          <div className={styles.card}>
          <Link href="/case/1">
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case1-thumb.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={700}
                    height={934}
                />
            </div>
            <div className={styles.card_title}>
              <p>
                <span>Case 1</span>
                <span>Male : 49 Years old</span>
              </p>
            </div>    
          </Link>       
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/case/2">
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case2-thumb.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={700}
                    height={934}
                />
            </div>
            <div className={styles.card_title}>
              <p>
                <span>Case 2</span>
                <span>Girl : 7 Years old</span>
              </p>
            </div>     
            </Link>          
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/case/3">
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case1-thumb.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={700}
                    height={934}
                />
            </div>
            <div className={styles.card_title}>
              <p>
                <span>Case 3</span>
                <span>Male : X Years old</span>
              </p>
            </div>            
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}