import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
// import styles from '../styles/mainmenu2.module.css'
import styles from '../styles/mainmenu.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function Main_menu() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Menu Ventilator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/mainmenu"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <header className={styles.headerbar1}>
        <p className='headerbar_text'>
          Ventilator
        </p>
      </header>
      <div className={styles.row}>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/menulearningmode"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/Ventilator-thumbnail.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Learning mode
              </p>
              {/* ใช้รูป Vent อันเดียวกันกับหน้า Introduction */}
            </div>   
            </Link>         
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/instruction/trouble-shooting"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/troubleshooting-thumbnail-2.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Trouble Shooting
              </p>
              {/* ใช้รูป ห้อง */}
            </div>      
            </Link>    
          </div>
        </div>
      </div>
    </div>
  )
}