import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
// import styles from '../styles/mainmenu2.module.css'
import styles from '../styles/mainmenu.module.css'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function Main_menu() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning mode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menuventilator"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
          </Link>
      </div>{/* prev_page */}
      <header className={styles.headerbar1}>
        <p className='headerbar_text'>
          Learning mode
        </p>
      </header>
      <div className={styles.row}>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/instruction/vent"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/Capturec-ventfinal-learning.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Interface introduction
              </p>
              {/* ใช้รูป Vent อันเดียวกันกับหน้า Introduction */}
            </div>   
            </Link>         
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href="/case/vent"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case1-thumb3.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Case scenario set up
              </p>
              {/* ใช้รูป คนไข้ */}
            </div>    
            </Link>           
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card}>
            <Link href='/instruction/simulator'>
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/Ventilator-thumbnail.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={504}
                    height={620}
                />
            </div>
            <div className={styles.card_title}>
              <p>
              Simulator
              </p>
              {/* ใช้รูป เครื่องอันเดียวกันกับเมนู Vent */}
            </div>         
            </Link>       
          </div>
        </div>
      </div>
    </div>
  )
}