import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/sitemap.module.scss'
import Link from "next/link";

export default function Select() {
  return (
    <div className={styles.container}>
      <Head>
        <title>sitemap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
