import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
// import styles from '../styles/mainmenu2.module.css'
import styles from '../styles/mainmenu-dev.module.scss'
import Link from "next/link";
// import { useRouter } from 'next/router'


export default function Main_menu() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Trouble Shooting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/menuventilator"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
          </Link>
      </div>{/* prev_page */}
      <header className={styles.headerbar1}>
        <p className='headerbar_text'>
        Trouble Shooting
        </p>
      </header>
      <div className={styles.row}>        
        <div className={styles.col_item}>
          <div className={styles.card2}>
            <Link href="/case/trouble-shooting2"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case3-thumb3.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title2}>
              <p>
              Patient 1
              </p>
              {/* ใช้รูป คนไข้ */}
            </div>    
            </Link>           
          </div>
        </div>
        <div className={styles.col_item}>
          <div className={styles.card2}>
            <Link href="/case/trouble-shooting"> 
            <div className={styles.card_thumbnail}>
              <Image
                    className={styles.bisitem}
                    src="/images/case4-thumb3.png"
                    alt="Ventilator"
                    // layout="fill"
                    // objectFit="cover"
                    width={640}
                    height={508}
                />
            </div>
            <div className={styles.card_title2}>
              <p>
              Patient 2
              </p>
              {/* ใช้รูป คนไข้ */}
            </div>    
            </Link>           
          </div>
        </div>
      </div>
    </div>
  )
}