import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../../styles/caseintro.module.css'
import Link from "next/link";
import { useRouter } from 'next/router'
import { useState , useEffect } from 'react';

export default function CaseMonitor() {
    const router = useRouter()
    const { id } = router.query
    let caseThumbnaiUrl = `/images/card${id}-rounded.png`
    if (id>3) {
        caseThumbnaiUrl = `/images/card1-rounded.png`
    }
    const nextUrl = `/case/${id}`
    const preUrl = `/case/${id}`
    const monitorUrl = `/case/monitor/${id}`

    let [countDown, setCountDown] = useState(5);
    let [countDownTrack, setCountDownTrack] = useState(null);

    // FN
    function countDownStart() {
        setCountDownTrack('start')
    }
    useEffect(() => {
        if ( countDownTrack == 'start' && countDown > 0) {
            setTimeout(() => {
                setCountDown(countDown - 1)
            }, 1000);
        }
    }, [countDown,countDownTrack]);
    

    return (
        <div className={styles.container}>
          <Head>
            <title>Introduction Case {id}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className='container'>
            <div className='row justify-content-center align-items-center min-h-screen'>
              <div className='col-11'>
                <div className={styles.case_wrapper}>
                  <div className='prev_page_case'>
                    <Link href={preUrl}> 
                      <Image
                          src="/images/prev.png"
                          alt="Women"
                          // layout="fill"
                          // objectFit="cover"
                          width={196}
                          height={196}
                      />
                      </Link>
                  </div>
                  <div className={styles.case_row}>
                    <div className={styles.case_colleft}>
                      <div className={styles.case_thumbnail}>
                        <Image
                            src={caseThumbnaiUrl}
                            alt="case1"
                            // layout="fill"
                            // objectFit="cover"
                            width={500}
                            height={500}
                        />
                      </div>
                      <div className={styles.case_simpledetail}>
                        <h2 className={styles.case_name}>Patient {id}</h2>
                        <div className={styles.case_simpledetail_byline}>
                          <ul>
                            <li>
                              Age : <strong>72 yrs. Old</strong>
                            </li>
                            <li>
                              Sex : <strong>Female</strong>
                            </li>
                            <li>
                              Weight : <strong>55 kg.</strong>
                            </li>
                            {/* <li>
                              Height : <strong>167 Cm</strong>
                            </li> */}
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className={styles.case_colright}>
                      <div className={styles.right_row}>
                        <div className={styles.right_colbox}>
                            <h2 className={styles.introduction_title}>Introduction</h2>
                            <p  className={styles.introduction_text}>
                                ผู้ป่วยอยู่ในภาวะ ARDS ถูก paralysed Ventilated ด้วยยา Neuromuscular blocking และมีการให้ยาระงับความรู้สึกด้วย propofol <br/>

                                Physical Examination:<br/>
                                BP 180/100 mmHG<br/>
                                HR 130 /min<br/>
                                RASS -5<br/>
                                No Hx HT<br/>
                                ไม่พบประวัติเป็นโรคความดันสูงมาก่อน
                            </p>
                        </div>
                      </div>
                      <div className={styles.btn_monitor_thumbnail_area}>
                        <div className={styles.btn_monitor_thumbnail}>
                          <Link href="/case/monitor/1"> 
                          <Image
                              src="/images/monitor.png"
                              alt="case1"
                              // layout="fill"
                              // objectFit="cover"
                              width={500}
                              height={500}
                          />
                          </Link>
                        </div>
                      </div>
                      <div className={styles.countdown_area}>
                            <div className={styles.countdown_btn}>
                                {countDown}
                            </div>
                      </div>
                      <div className={styles.btn_area}>
                        <button 
                        onClick={countDownStart}
                        className={styles.next_btn}>
                          NEXT
                        </button>
                      </div>
                    </div>
                    {/* case_colright */}
                  </div>
                </div> 
              </div>          
            </div>
          </div>
        </div>
    )
}