import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/instruction/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';

export default function Intruction_1() {
    const router = useRouter()
    const [instructionStep, setInstructionStep] = useState(1);
    const [instructionText, setInstructionText] = useState('การติดเซ็นเซอร์เริ่มต้นจากบริเวณกลางหน้าผาก ซึ่งคือตำแหน่งของ อิเล็กโทรดหมายเลข 1 ');
    const handleClick = () => {
        console.log('click')
        setInstructionStep(instructionStep+1)
        if (instructionStep == 1) {
            setInstructionText('ในหัวข้อนี้ท่านต้องปรับตำแหน่งของ อิเล็กโทรดหมายเลข 1 ให้ถูกต้อง โดยการเลือกบริเวณที่จะติดอิเล็กโทรด และทิศทางที่ถูกต้องของอิเล็กโทรด')
        }
        if (instructionStep == 2) {
            setInstructionText('โดยกดปุ่มซ้ายของเมาส์เพื่อจับอุปกรณ์ และหมุนลูกศรเพื่อปรับทิศทาง')
        }
        if (instructionStep == 3) {
            router.push('/brain/install')
            document.documentElement.requestFullscreen();
        }
    };
    function toggleFullScreen() {
        if (!document.fullscreenElement) {
          document.documentElement.requestFullscreen();
        } else if (document.exitFullscreen) {
          document.exitFullscreen();
        }
    }
    function getFullScreen() {
        document.documentElement.requestFullscreen();
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Consent</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='prev_page'>
                <Link href="/mainbrain"> 
                <Image
                    src="/images/prev.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={196}
                    height={196}
                />
                </Link>
            </div>{/* prev_page */}

            <div className='container'>
                <div className='row justify-content-center align-items-center min-h-screen'>
                    <div className='col-11'>
                        <div className={styles.intruction_wrapper}>
                            <div className='row'>
                                <div className='col-3'>
                                    <div className={styles.thumbnail_frame}>
                                        <Image
                                            src="/images/imageBrain2.png"
                                            alt="Women"
                                            // layout="fill"
                                            objectFit="contain"
                                            width={1200}
                                            height={1200}
                                        />
                                    </div>
                                </div>
                                <div className='col-9'>
                                    <div className={styles.content_container}>
                                        <div className={styles.contenn_wrap}>
                                            <h2>Instruction</h2>
                                            <p className={styles.text_lg}>
                                                {instructionText}
                                            </p>
                                        </div>
                                    </div>  
                                </div>
                            </div>
                            <div className={styles.btn_area}>
                                <div className={styles.btn_container}>
                                    {/* <Link href="/brain/install">  */}
                                    <button className={styles.next_btn} onClick={handleClick}>
                                    NEXT
                                    </button>
                                    {/* </Link> */}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
    )
}
