import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/instruction/main.module.scss'
import Link from "next/link";
import { useRouter } from 'next/router'

export default function Intruction_1() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Consent</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='prev_page'>
                <Link href="/menulearningmode"> 
                <Image
                    src="/images/prev.png"
                    alt="Women"
                    // layout="fill"
                    // objectFit="cover"
                    width={196}
                    height={196}
                />
                </Link>
            </div>{/* prev_page */}

            <div className='container'>
                <div className='row justify-content-center align-items-center min-h-screen'>
                    <div className='col-11'>
                        <div className={styles.intruction_wrapper}>
                            <div className='row'>
                                <div className='col-3'>
                                    <div className={styles.thumbnail_frame}>
                                        <Image
                                            src="/images/Capturec-ventfinal-learning.png"
                                            alt="Women"
                                            // layout="fill"
                                            objectFit="cover"
                                            width={1200}
                                            height={1200}
                                        />
                                    </div>
                                </div>
                                <div className='col-9'>
                                    <div className={styles.content_container}>
                                        <div className={styles.contenn_wrap}>
                                            <h2>Instruction</h2>
                                            <p>
                                                ก่อนอื่นเลย เรามาทำความรู้จักพารามิเตอร์ และปุ่มต่างๆของเครื่องช่วยหายใจกัน
                                            </p>
                                            {/* <ul>
                                                <li>Flow trigger 5L/min</li>
                                                <li>PEEP 5 cmH2O </li>
                                                <li>ให้ pressure support 10 cmH2O </li>
                                                <li>เนื่องจากคนไข้มีภาวะของ Airway resistance เลยอยากปรับ rise time เป็น 75% </li>
                                                <li>%O2 : 40 </li>
                                                <li>พบว่าคนไข้มี delay cycling เลยปรับ Esens 50%</li>
                                                <li>ปรับหน้าจอให้เป็น 3 Waveform</li>
                                            </ul>                                             */}
                                        </div>
                                    </div>  
                                </div>
                            </div>
                            <div className={styles.btn_area}>
                                <div className={styles.btn_container}>
                                    <Link href="/vent/instruction"> 
                                    <button className={styles.next_btn}>
                                    NEXT
                                    </button>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
    )
}
