import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../../styles/casemonitor.module.css'
import Link from "next/link";
import { useRouter } from 'next/router'

export default function CaseMonitor() {
    const router = useRouter()
    const { id } = router.query
    const nextUrl = `/case/introduction/${id}`
    return (
        <div className={styles.container}>
            <Head>
                <title>Monitor case {id} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='container position-relative'>
                <div className='row justify-content-center align-items-center'>
                    <div className='col-7 py-4'>
                        <Image
                            src="/images/case-monitor-demo.png"
                            alt="Women"
                            // layout="fill"
                            // objectFit="cover"
                            className='rounded-4'
                            width={2272}
                            height={2024}
                        />
                    </div>
                </div>
            </div>
            <div className={styles.btn_area}>
                <Link href={nextUrl}> 
                <button className={styles.next_btn}>
                    NEXT
                </button>
                </Link>
            </div>
        
        </div>
    )
}